# Generated by Django 2.2.1 on 2019-05-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JumiaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('discount', models.IntegerField()),
                ('image', models.CharField(max_length=200)),
                ('is_global', models.BooleanField(default=False)),
                ('link', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PriceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.JumiaItem')),
            ],
        ),
    ]
